version: "3"

services:
  reverseproxy:
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: "Dockerfile"
    ports:
      - 3000:80
      - 4000:81
    restart: always
  
  app1:
    container_name: app1
    depends_on:
      - reverseproxy
    build:
      context: ./app1
      dockerfile: "Dockerfile"
    ports:
      - 80:3000
    restart: always

  app2:
    container_name: app2  
    depends_on:
      - reverseproxy
    build:
      context: ./app2
      dockerfile: "Dockerfile"
    ports:
      - 81:3000
    restart: always